package dataaccess;
import model.Model;

interface UserDAO {
    Model.UserData getUser(String username) throws DataAccessException;
    void createUser(Model.UserData newUsername);
    Boolean matchingPassword(Model.UserData user);
    void clearUserDAO();
}

// Table: Primary key (id - AUTOGENERATED)
// username, password, email - NOT NULL
// Connects to auth via username, since it must be unique to a user